name: antonio
favicon: null
layout_spectrum: 0.17043
typography_spectrum: 0.51642
title: Perfil personal
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060409'
    - '#c5b49a'
    - '#ebdcc9'
    - '#522a2b'
    - '#a6656d'
  brandStrength: 0.6875
  lightness: 0.6875
  saturation: 0.375
  rhythmicContrast: 1
purpose: []
